services:
  app:
    container_name: application-server
    image: wb:latest
    restart: always
    user: root
    entrypoint: ["/bin/bash", "-c"]
    command: ["ttyd -W -p 7681 bash"]
    volumes:
      - /workspace:/workspace:cached
      - work:/home/vscode/work
    ports:
      - "7681:7681"
    networks:
      - app-network
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined

volumes:
  work:

networks:
  app-network:
    external: true